# Generated by Django 3.0.7 on 2020-06-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fltapitest', '0002_auto_20200621_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fltapitest.User'),
        ),
    ]
