# Generated by Django 3.0.7 on 2020-06-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fltapitest', '0003_auto_20200621_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityperiods', to='fltapitest.User'),
        ),
    ]
