# Generated by Django 3.0.7 on 2020-06-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fltapitest', '0005_auto_20200627_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='activityperiod',
            old_name='start',
            new_name='start_time',
        ),
    ]
